### ISSUE TITLE
multiline selections

### ISSUE THREAD

**Issue by callumlocke** [leny/atom-coffeescript-check#2] opened 2014-08-12 23:05 UTC
if you select multiple lines that are indented, but don't select the indent on the first line, like this...

```
                     █ █ █ █ █ █ █ █ █ █ █ █ █
█ █ █ █ █ █ █ █ █ █ █ ██ █ █ █ █ █ █ █ █ █ █ █
█ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █
```

..it would be nice if this plugin could add the initial indent from the first line to the selection (providing it is just whitespace). ie, if the selection starts mid-line and contains newlines, then it should add any missed-off indent from before the selection on the first line.

currently if you miss off the indent from the first line in the selection it causes an error.

**Comment by leny** [comment] 2015-05-24 15:34
Hi, 

Sorry for the (very) long delay.

I've made some fixes in the package for the atom 1.0 API changes, and I can't reproduce the bug anymore.

*Seems* to be fixed in version `0.1.0`. Thanks for the report.

**Closed by leny** 2015-05-24 15:34 UTC
